os: linux
dist: focal
language: node_js
node_js:
  - 14

services:
  - docker

before_install:
  - docker build -t andre2ar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andre2ar/react-test npm test

after_success:
  - docker build -t andre2ar/fibonnaci-client ./client
  - docker build -t andre2ar/fibonnaci-nginx ./nginx
  - docker build -t andre2ar/fibonnaci-server ./server
  - docker build -t andre2ar/fibonnaci-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push andre2ar/fibonnaci-client
  - docker push andre2ar/fibonnaci-nginx
  - docker push andre2ar/fibonnaci-server
  - docker push andre2ar/fibonnaci-worker